#THIS WORKFLOW FILE CAN ONLY BE USED IN TESTS
on:
  push:
    branches:
      - canary

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Get version information
        id: version_info
        run: |
          LATEST_RELEASE=$(curl --silent "https://api.github.com/repos/Ryubing/Canary-Releases/releases/latest" | jq -r .tag_name)
          echo "build_version=$LATEST_RELEASE" >> $GITHUB_OUTPUT
        shell: bash
        
      - name: Create tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.version_info.outputs.build_version }}',
              sha: context.sha
            })

  build-and-release:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check update & Write version information
      # fuck powershell's default output is encoded in UTF-16LE
        run: |
          $PSDefaultParameterValues['Out-File:Encoding'] = 'utf8'
          $PSDefaultParameterValues['Out-File:Encoding'] = 'Default'
          $response = Invoke-RestMethod -Uri "https://api.github.com/repos/Ryubing/Canary-Releases/releases/latest"
          $tag_name = $response.tag_name
          $previous_tag_name = cat ryujinx_canary_latest_tag.flag
          if ($tag_name -eq $previous_tag_name) {
            echo No newer version has been found.
            exit 1
          }         
          else {
            echo $tag_name > ryujinx_canary_latest_tag.flag
          }
        shell: powershell
      
      - name: Commit version information
        run: |
          git config --global user.name 'LuccaWang404'
          git config --global user.email 'jh327063592@163.com'
          git add ryujinx_canary_latest_tag.flag
          git commit -m "Canary Version Update"
        shell: powershell
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      
      - name: Save version and date information to $env
        id: version_info
        run: |
          $response = Invoke-RestMethod -Uri "https://api.github.com/repos/Ryubing/Canary-Releases/releases/latest"
          $tag_name = $response.tag_name
          echo "build_version=$tag_name" >> $env:GITHUB_OUTPUT
          $build_date = Get-Date
          $build_date = $build_date.ToUniversalTime().AddHours(8)
          echo "build_date=$build_date" >> $env:GITHUB_OUTPUT
        shell: powershell
      - name: Download & extract latest release
        run: |
          wget -o ryujinx-${{ steps.version_info.outputs.build_version }}-win_x64.zip https://github.com/Ryubing/Canary-Releases/releases/download/${{ steps.version_info.outputs.build_version }}/ryujinx-canary-${{ steps.version_info.outputs.build_version }}-win_x64.zip
          wget -o ryujinx-canary-source-${{ steps.version_info.outputs.build_version }}.zip https://git.ryujinx.app/ryubing/ryujinx/-/archive/Canary-${{ steps.version_info.outputs.build_version }}/ryujinx-Canary-${{ steps.version_info.outputs.build_version }}.zip
          7z x ryujinx-canary-${{ steps.version_info.outputs.build_version }}-win_x64.zip
        shell: powershell

      - name: Generate new .iss script
      # fuck powershell's default output is encoded in UTF-16LE
        run: |
          $PSDefaultParameterValues['Out-File:Encoding'] = 'utf8'
          $PSDefaultParameterValues['Out-File:Encoding'] = 'Default'
          echo '#define ExecutableVersion "${{ steps.version_info.outputs.build_version }}"' > autocompile.publish.tmp.script.canary.iss
          type autocompile.publish.base.script.canary.iss >> autocompile.publish.tmp.script.canary.iss
        shell: powershell

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.1.0
        with:
          path: autocompile.publish.tmp.script.canary.iss
          options: /O+
          
      - name: Pushing new release
        uses: ncipollo/release-action@v1.13.0
        with:
          name: ${{ steps.version_info.outputs.build_version }}
          artifacts: "*.zip, build/*.exe"
          tag: ${{ steps.version_info.outputs.build_version }}
          body: "## üê≤ Ryujinx Installer Canary Release v ${{ steps.version_info.outputs.build_version }} - Ryubing Fork

                  ![GitHub Actions Badge](https://img.shields.io/badge/GitHub%20Actions-181717?logo=github&logoColor=fff&style=flat)</br>
                  ***This release was generated by GitHub Actions.***</br>
                  ***Build Time: ${{ steps.version_info.outputs.build_date }} , UTC+8; Version: ${{ steps.version_info.outputs.build_version }}***</br></br>
                  This release contains the auto-compiled installer of Ryujinx Emulator ***v ${{ steps.version_info.outputs.build_version }} (Ryubing Fork)***.</br>
                  If you want to check out the update details of each version, please view the release page to see the [**Changelog**](https://git.ryujinx.app/ryubing/ryujinx/-/compare).</br>
                  
                  > [!TIP]</br>
                  **This project can check for updates regularly and build the installers instantly by GitHub Actions, so it is generally synchronized with the progress of the [Ryubing Fork](https://git.ryujinx.app/ryubing/ryujinx/-/releases).**"
          omitBodyDuringUpdate: true
          allowUpdates: true
          replacesArtifacts: true
          owner: "LuccaWang404"
          repo: "Ryujinx-installers"
          token: ${{ secrets.GITHUB_TOKEN }}
